---
- name: Playbook para Parchar Servidores Linux
  hosts: all
  #become_user: 
  become: true
  tasks:
    - name: Parchar Servidor Linux
      shell: yum -y update
      register: update_result
      tags: Parchar-Server

    - name: Verificar si el kernel fue actualizado
      shell: "echo '{{ update_result.stdout }}' | grep -q 'kernel'"
      register: kernel_updated
      failed_when: false
      changed_when: false
    
    - name: Reiniciar Servidor Linux
      reboot:
        reboot_timeout: 180
      when: kernel_updated.rc == 0
      tags: Reiniciar-Server