---
- name: Playbook para Parchar Servidores Linux
  hosts: all
  #become_user: 
  become: true
  tasks:
    - name: Instalar dnf-utils (si no está instalado)
      ansible.builtin.dnf:
        name: dnf-utils
        state: present

    - name: Actualizar todos los paquetes
      ansible.builtin.dnf:
        name: "*"
        state: latest
      register: dnf_update
      tags: Parchar-Server

    - name: Verificar si es necesario reiniciar el sistema
      shell: needs-restarting -r
      register: restart_needed
      failed_when: restart_needed.rc not in [0, 1]
      changed_when: restart_needed.rc == 1

    - name: Reiniciar Servidor Linux si es necesario
      reboot:
        reboot_timeout: 180
      when: restart_needed.rc == 1
      tags: Reiniciar-Server