---
- name: Playbook para Parchar Servidores Linux
  hosts: all
  #become_user: 
  become: true
  tasks:
    - name: Parchar Servidor Linux
      shell: yum -y update
      tags: Parchar-Server
    
    - name: Reiniciar Servidor Linux
      reboot:
        reboot_timeout: 180
        become: yes
        #when: inventory_hostname in ["node1", "node2", "node3"]